name: seed_labels_update

on:
  schedule:
    - cron: "0 0 * * 1" # At 00:00 on Monday

env:
  ACCOUNT: "${{ secrets.ACCOUNT }}"
  ROLE: "${{ secrets.ROLE }}"
  USER: "${{ secrets.USER }}"
  PASSWORD: "${{ secrets.PASSWORD }}"
  REGION: "${{ secrets.REGION }}"
  DATABASE: "${{ secrets.DATABASE }}"
  WAREHOUSE: "${{ secrets.WAREHOUSE }}"
  SCHEMA: "${{ secrets.SCHEMA }}"

jobs:
  scheduled_run:
    name: seed_labels_update
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo content
        uses: actions/checkout@v2 # checkout the repository content to github runner

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9" # install the python version needed

      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r python_scripts/requirements.txt

      - name: execute py script # run main.py
        run: python python_scripts/token_labels_retriever.py

      - name: seed the token labels # run main.py
        run: dbt seed --full-refresh

      - name: run the affected tables # run main.py
        run: dbt run -s silver__token_labels+ silver__prices_oracle+ --full-refresh

      - name: check for changes
        run: git status

      - name: stage changed files
        run: git add .

      - name: commit changed files
        run: |
          git config user.email "abc@xyz"
          git config user.name "github-actions"
          git commit -am "Auto-update token labels"

      - name: push changes to labels
        run: |
          git push
